# Generated by Django 4.2.6 on 2023-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filtrarreceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia', models.CharField(max_length=50)),
                ('intolerancia', models.CharField(max_length=50)),
                ('comidadetestavel', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=8)),
                ('culinarias_preferidas', models.ManyToManyField(to='recipe.culinaria')),
            ],
        ),
    ]
